---
fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    concat: https://github.com/puppetlabs/puppetlabs-concat
    extlib: https://github.com/voxpupuli/puppet-extlib
    systemd: https://github.com/voxpupuli/puppet-systemd
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core
    postgresql: https://github.com/puppetlabs/puppetlabs-postgresql
